apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echo-server
  namespace: echo-server
spec:
  interval: 1m
  releaseName: echo-server
  chart:
    spec:
      chart: ./apps/echo-server/charts
      sourceRef:
        kind: GitRepository
        name: echo-server
  values:
    image:
      tag: 0.9.2    